## 3. ndarray 만들기

### 3.2 정해진 shape으로 ndarray 만들기

- 데이터 초기화할때 많이 쓰임 
- numpy.zeros(shape, dtype=float, order='C', * , like=None)

In [1]:
import numpy as np

M = np.zeros(shape=(2,3))

In [2]:
print(M.shape)
print(M)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


- numpy.ones(shape, dtype=None, order='C',* , like=None)

In [3]:
M = np.ones(shape=(2,3))
print(M.shape)
print(M)

(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]


- numpy.full(shape, fill_value, dtype=None, order='C', * , like=None)
- ndarray with Specific Values

In [4]:
M =np.full(shape=(2,3), fill_value=3.14)
print(M.shape)
print(M)

(2, 3)
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


- numpy.empty(shape, dtype=float, order='C', * , like=None)

메모리상에서 빈자리만 만들어놔라 (어떤 변수나 함수에서 사용했었던 메모리값을 그대로 사용)

In [5]:
M =np.empty(shape=(2,3))
print(M.shape)
print(M)

(2, 3)
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


### 1. like라는 관점 (해당 tensor 와 비슷한)

- numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)
- numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)

In [10]:
import numpy as np
M = np.full(shape=(2, 3), fill_value=3.14)
print(M, '\n')

zeros_like = np.zeros_like(M)
ones_like = np.ones_like(M)
full_like = np.full_like(M, fill_value=100)
empty_like = np.empty_like(M)

print("zeros_like: \n", zeros_like, '\n')
print("ones_like: \n", ones_like, '\n')
print("full_like: \n", full_like, '\n')
print("empty_like: \n", empty_like, '\n')

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]] 

zeros_like: 
 [[0. 0. 0.]
 [0. 0. 0.]] 

ones_like: 
 [[1. 1. 1.]
 [1. 1. 1.]] 

full_like: 
 [[100. 100. 100.]
 [100. 100. 100.]] 

empty_like: 
 [[100. 100. 100.]
 [100. 100. 100.]] 

