## Indexing and Slicing Vector ndarrays


In [1]:
import numpy as np
a = np.arange(10)
print(f"ndarray: \n{a}\n")
      

print("a[0] : ", a[0])
print("a[2] : ", a[2])

print("a[-1] : ", a[-1]) # the last element
print("a[-2] : ", a[-2]) #

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[0] :  0
a[2] :  2
a[-1] :  9
a[-2] :  8


In [2]:
a = np.arange(5)
print(f"ndarray: \n{a}\n")

for data in a:
 print(data)

ndarray: 
[0 1 2 3 4]

0
1
2
3
4


In [3]:
import numpy as np
a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[0:3] : ", a[0:3])
print("a[3:7] : ", a[3:7])
print("a[5:-1] : ", a[5:-1])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[0:3] :  [0 1 2]
a[3:7] :  [3 4 5 6]
a[5:-1] :  [5 6 7 8]


In [4]:
import numpy as np
a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[2:] : ", a[2:])
print("a[-2:] : ", a[-2:]) # the last two elements
print("a[:5] : ", a[:5])
print("a[:-3] : ", a[:-3])
print("a[:] : ", a[:])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:] :  [2 3 4 5 6 7 8 9]
a[-2:] :  [8 9]
a[:5] :  [0 1 2 3 4]
a[:-3] :  [0 1 2 3 4 5 6]
a[:] :  [0 1 2 3 4 5 6 7 8 9]


In [5]:
import numpy as np
a = np.arange(10)
print(f"ndarray: \n{a}\n")
print("a[2:7:2] : ", a[2:7:2])
print("a[::3] : ", a[::3])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:7:2] :  [2 4 6]
a[::3] :  [0 3 6 9]


In [6]:
import numpy as np
a = np.arange(10)
print(f"ndarray: \n{a}\n")
# 7부터 시작해서 2가되기 전까지 인데 방향을 반대로
print("a[7:2:-1] : ", a[7:2:-1])
print("a[::-1] : ", a[::-1])
print("a[8:3:-2] : ", a[8:3:-2])
# 전체다 가져오는데 3칸씩 띄어서
print("a[::-3] : ", a[::-3])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[7:2:-1] :  [7 6 5 4 3]
a[::-1] :  [9 8 7 6 5 4 3 2 1 0]
a[8:3:-2] :  [8 6 4]
a[::-3] :  [9 6 3 0]


In [7]:
import numpy as np
a = np.arange(10)
indices = np.array([0, 3, 6, -1])

print(f"ndarray: \n{a}\n")
#전부다 같은 의미임
print(a[[0, 3, 6, -1]])
print(a[indices])
print(a[a%3==0])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

[0 3 6 9]
[0 3 6 9]
[0 3 6 9]
